trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:

- checkout: none

- script: |
    git clone -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" "$(Build.Repository.Uri)" s
  displayName: Checkout the repo
